export const MyIconFontList = [
    { type: "iconfood-cookie", spin: true },
    { type: "iconfood-pecan", spin: false },
    { type: "iconfood-avocado", spin: true },
    { type: "iconfood-pudding", spin: false },
    { type: "iconfood-strawberry", spin: true },
    { type: "iconfood-doughnut", spin: false },
    { type: "iconfood-chips", spin: false },
    { type: "iconfood-popcorn", spin: true },
    { type: "iconfood-bread", spin: false },
    { type: "iconfood-pizza", spin: true },
    { type: "iconfood-hotdog", spin: false },
    { type: "iconfood-taco", spin: true },
    { type: "iconfood-popsicle", spin: true },
    { type: "iconfood-eggyolkcake", spin: true },
    { type: "iconfood-sushi", spin: false },
    { type: "iconfood-cake", spin: true },
    { type: "iconfood-macaron", spin: true },
    { type: "iconfood-cashew", spin: false },
    { type: "iconfood-mochi", spin: false },
    { type: "iconfood-pistachio", spin: true },
]
